### PR TITLE
Add git-tfs 0.15

### PR DESCRIPTION
**Pull request by anaisbetts**
This PR adds git-tfs (http://git-tfs.com/) to our version of MSysGit, for those poor unfortunate souls who are forced to use TFS

### CODE REVIEW

**Comment by half-ogre** [comment]
Looks good, though I didn't actually pull it down and give it a go. Do we need to add a license or anything to distribute this?

:+1:

**Comment by aroben** [comment]
Can you document how you did this, and how we can update it in the future?

**Comment by anaisbetts** [comment]
@aroben  Unzip git-tfs.zip, dump contents into `bin` folder, remove `.pdb` files - easy peasy

**Comment by aroben** [comment]
Sweet. Wanna dump a script into either the root or `share/WinGit` to do it?

**Comment by half-ogre** [comment]
I'll add a script as part of pulling this in.

**Comment by half-ogre** [comment]
@xpaulbettsx @aroben Let me know if that looks good, and if so, I'll merge it and pull it into GHfW.

**Comment by aroben** [comment]
Nice work @half-ogre!

It feels a little weird for the license to be in `bin/`. Maybe it should end up in the root of the packaged distribution? The bottom of `share/WinGit/copy-files.sh` is where other files get copied into the root. I'm not totally sure where it should live on `devel` though. In some ways it would be nice for all the `git-tfs` stuff to go in its own directory and then get copied to the right place by `copy-files.sh`, but maybe that's overcomplicating things.

**Comment by half-ogre** [comment]
@aroben It felt weird to me for it to be in `bin` too, but it also felt weird for it not to be alongside the git-tfs files. I like the idea of keeping them all in a separate directory and using `copy-files.sh`. Where would that directory live? in `share`?

**Comment by aroben** [comment]
If we were to do this the msysGit Way(tm), we'd create a `src/git-tfs` directory that contained a script that would download a particular version of the git-tfs source, compile it, and install it into the appropriate directories. I'm not sure it's worth going that far though.

It's interesting that there don't seem to be license files for any of the software in `src/` lying around anywhere.

Anyway, back to your question. Putting it in `share/git-tfs` sounds good to me.

**Comment by half-ogre** [comment]
@aroben I only brought up including the license file as a question; if we don't think it's needed, we can leave this stuff in bin without it and call it a day. :)

**Comment by aroben** [comment]
I think including it is a good idea. Let's go ahead and put stuff in `share/git-tfs` and make `copy-files.sh` drop them in the right place when packaging up the distribution.

**Comment by half-ogre** [comment]
Can you take one last look @aroben? Is that the only change I need to make to `copy-files.sh`?

**Comment by aroben** [comment]
Looks great! I'd just try running the `ghfw-release.sh` script to make sure everything ends up in the right place (if you haven't already). (And of course you'll need to do that anyway to update the `PortableGit` branch.)

**Pull request merged**
