### PR TITLE
removed "origin" fetch refspecs

### PR DESCRIPTION
**Pull request by shiftkey**
cc @matthewmccullough 

I'll writeup some notes on how this will impact GHfW

### CODE REVIEW

**Comment by matthewmccullough** [comment]
@github/training-teachers A heads-up to the much-appreciated change from Brendan for the `git remote add` versus `git remote set-url` discussion in https://github.com/github/training-team/issues/659#issuecomment-37945255

**Comment by PeterBell** [comment]
YAY! Awesome - this'll make teaching class easier for sure once it's out and widely used!

**Comment by jordanmccullough** [comment]
Thanks for the mention and to Brendan for the change. Will make class so much easier.

**Comment by half-ogre** [comment]
So, we're :+1: to removing this now? I haven't caught up on email and mentions, but I thought @paulcbetts cared quite a bit about keeping this so PRs would fetch from the shell.

**Comment by shiftkey** [comment]
@half-ogre Yeah, that's the part I'm torn over too. 

We could modify our repo creation process in GHfW to add these refspecs to the `.git/config`. But our existing repos obviously don't do this, so it's a bit of a sticky situation.

**Comment by half-ogre** [comment]
If we could make adding it per-repo **solid** it might nice, but I'm definitely a big :+1: to removing it from system-level config regardless (and we can make it an optional thing while keeping Clone PR to Desktop working). We'll need to make sure that GHfW's fetch is handling this once we remove it (I think I added that, but I can't recall for sure now). 

@paulcbetts, you on board with this?

**Comment by anaisbetts** [comment]
Why don't we just fix this in Git, I feel like we're throwing the baby out with the bathwater here. All we need to do is write an extra `if` statement to consider remotes that have no URL to be non-existent. Entirely reasonable patch to make.

**Comment by shiftkey** [comment]
@paulcbetts will that also fix the set-url workaround that @matthewmccullough was talking about?

**Comment by shiftkey** [comment]
Relevant reading: [the remote exists](https://github.com/git/git/blob/7794a680e63a2a11b73cb1194653662f2769a792/builtin/remote.c#L183) and [building up the remotes collection](https://github.com/git/git/blob/5172cb3bcb2c7e1a609e34cfae64e3b181e0226a/remote.c#L335)

**Comment by half-ogre** [comment]
> Why don't we just fix this in Git

There's the issue of it not working with older versions of Git, but I could live with that. Can we take it out until that fix is in Git, and add it back in when it is?

**Comment by anaisbetts** [comment]
@half-ogre I'll have a PR in a minute to fix this

**Comment by half-ogre** [comment]
> /cc github/git-msysgit#1

Nice. And because we put the refspecs in the system-level config, it would only affect our shell and not other Git installs. This could work.

**Comment by half-ogre** [comment]
Shall we close this in favor of pulling in github/git-msysgit#1 when it comes in?

**Comment by niik** [comment]
Cherry picked this commit on top of devel so it's mergeable /cc https://github.com/github/Windows/issues/1134

**Comment by joshvera** [comment]
https://github.com/github/git-msysgit/pull/1 seems to have stalled and we need this in sooooo

deal-with-it

**Pull request merged**
