### PR TITLE
Fetch PRs as part of git fetch

### PR DESCRIPTION
**Pull request by anaisbetts**
https://gist.github.com/piscisaureus/3342247

This makes it so that every time we fetch, we'll get the refs for all of the Pull Requests as well. On github/windows, fetching every PR for all time resulted in an extra 2MB of downloaded data, I'm not too worried about this from a perf standpoint.

### CODE REVIEW

**Comment by anaisbetts** [comment]
This needs to be paired with a fix in GH4W, because we currently display the refs that this pulls down, which is Bad™ and technically incorrect because it's not what `git branch` displays

**Comment by aroben** [comment]
Does this cause errors for non-GitHub remotes?

**Comment by anaisbetts** [comment]
@aroben Good question. I don't think it will, but I'll make sure

**Comment by anaisbetts** [comment]
@aroben Nope, looks like everything is kosher.

**Pull request merged**
