### PR TITLE
Always use the x86 git-tfs native binary

### PR DESCRIPTION
**Pull request by half-ogre**
Native git-tfs binaries were added with a recent git-tfs update, but the release script wasn't updated to pull them in, so git-tfs in the GitHub for Windows shell isn't working.
## To-Do
- [x] Is it okay to always use the x86 binary?
- [x] test

cc @spraints @github/windows

### CODE REVIEW

**Comment by half-ogre** [comment]
I gave the x86 version on my x64 laptop a minimal test and seems fine. @spraints, do you see any issues with just always using the x86 binary?

@github/windows, a review if you please?

**Comment by shiftkey** [comment]
This seems like a reasonable workaround. I'll let @spraints chime in on the x86/x64 dangers (if any exist)...

**Comment by half-ogre** [comment]
@spraints We're going to run with this for now, as it appears to work, but please do let me know there are issues we might have missed.

**Comment by spraints** [comment]
:+1:

For now, git-tfs always runs as 32 bit in order to support vs 2008 tfs client libraries. It has the NativeBinaries folder because that's what libgit2sharp does with its libgit2 dependency.

At some point, git-tfs will drop support for vs 2008 and switch git-tfs to AnyCPU. So, eventually this will stop working. I'm fine with figuring out the right fix when that happens.

**Pull request merged**
