### PR TITLE
Fix release script after recent git-tfs changes

### PR DESCRIPTION
**Pull request by half-ogre**
9a7883e broke the release script, as it was still referencing `git-tfs/*/xml`. This fixes that.

**Tests**
- [x] run `ghhw-release.sh` with the changes

@spraints or @github/windows, can I get a review please?

### CODE REVIEW

**Comment by haacked** [comment]
Why's referencing XML bad? I mean, change looks good to me, but I don't understand it. :smile:

**Comment by half-ogre** [comment]
> Why's referencing XML bad? I mean, change looks good to me, but I don't understand it. 

Because 9a7883e removed said .xml files

**Comment by haacked** [comment]
:shipit:

**Comment by spraints** [comment]
:+1:

**Pull request merged**
